name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  percent_indicator: ^4.2.4
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/analytic_icon.svg
    - assets/icons/arrow_in_cube_down_icon.svg
    - assets/icons/arrow_in_cube_up_icon.svg
    - assets/icons/car_icon.svg
    - assets/icons/done_in_cube_icon.svg
    - assets/icons/fork_and_knife_icon.svg
    - assets/icons/home_icon.svg
    - assets/icons/money_icon.svg
    - assets/icons/transfers_icon.svg
    - assets/icons/person_icon.svg

  uses-material-design: true
